// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9ljkSEDbtwJj5C_7k_6K54JOe7ISZLds',
    appId: '1:397809197438:web:e35e582ab24f28e5b7932f',
    messagingSenderId: '397809197438',
    projectId: 'hsnew-a78fd',
    authDomain: 'hsnew-a78fd.firebaseapp.com',
    storageBucket: 'hsnew-a78fd.appspot.com',
    measurementId: 'G-YNGCQ52H13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCecHEUP7XBRK7_Bb4agkpFMGX9O7IQj5E',
    appId: '1:397809197438:android:a58c1e50d1d73d2bb7932f',
    messagingSenderId: '397809197438',
    projectId: 'hsnew-a78fd',
    storageBucket: 'hsnew-a78fd.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhHYz3UtmASsHPncQreHS9Uk18cWhlnZY',
    appId: '1:397809197438:ios:4b6ea97b72401af0b7932f',
    messagingSenderId: '397809197438',
    projectId: 'hsnew-a78fd',
    storageBucket: 'hsnew-a78fd.appspot.com',
    iosClientId: '397809197438-mbl3d8961r2vet5cgmkuft09nuoo56ih.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterHs',
  );
}
